add files for mobile app
getsmarter/moodle-mod_groupselect pull request #1
Opened 2019-07-08 12:17 UTC by rumanod

https://jira.2u.com/browse/CTED-60

2019-07-08 12:37 UTC, JJSwanevelder commented on appjs/app_init.js
> +        console.log(this.pattern);
Please remove this

2019-07-08 12:38 UTC, JJSwanevelder commented on appjs/app_init.js
> +        console.log('PP2');
Please remove

2019-07-08 12:39 UTC, JJSwanevelder commented on classes/output/mobile.php
> +        $accessall = has_capability ( 'moodle/site:accessallgroups', $context );
Not sure if we should have so many open spaces and for the few lines below the same

2019-07-08 12:41 UTC, JJSwanevelder commented on classes/output/mobile.php
> +            if (in_array ( $group->id, $passwordgroups )) {
Can use turnerary statement if it fits in reasonable line length.

2019-07-08 12:42 UTC, JJSwanevelder commented on classes/output/mobile.php
> +                        ) );
Weird spacing here.

2019-07-08 12:42 UTC, PPrinsloo requested changes

2019-07-08 12:42 UTC, PPrinsloo commented on appjs/app_init.js
> +                    console.log('PP1');
Please remove.

2019-07-08 12:43 UTC, JJSwanevelder commented on classes/output/mobile.php
> +        //$data = json_decode (json_encode ($data), FALSE);
Remove please

2019-07-08 12:46 UTC, JJSwanevelder commented on templates/mobile_view_add_new_group.mustache
> +{{=<% %>=}}
Not sure what is the reason for this file if only this line is here.

2019-07-08 12:47 UTC, JJSwanevelder commented on templates/mobile_view_groupselect.mustache
> +    <ion-item style="background-color: #f7f7f7;">
If possible do all styling in the stylesheets. We should only continue with this styling if we dynamically bind angular styles. Even so we can dynamically bind classes.

2019-07-08 12:48 UTC, JJSwanevelder requested changes
Hey @rumanod please see suggested changes.

2019-07-09 09:16 UTC, JJSwanevelder approved these changes
👍

2019-07-09 09:21 UTC, merged